### ISSUE TITLE
Connection to postgis

### ISSUE THREAD

**Issue by gioargyr** [gmouchakis/docker-postgis#1]
Hi!
I was testing the connection between Strabon and PostGis in the SC7 Pilot and realized that apart from the port, I had to specify "container_name: postgis" to achieve the connection. Neither the hostname nor the name of the service of postgis were of great importance.
Are you aware of that?
How can the container_name of postgis is more important than its hostname, given that in Strabon's  connection-properties I have a field "hostname: postgis"?

**Comment by gmouchakis** [comment]
Can you provide the docker-compose file or the docker commands you used to deploy the containers so I can check this?

**Comment by gioargyr** [comment]
I should inform you that there is no problem how postgis achieves that. I was just asking because it seemed a bit strange. Also, docker-postgis can achieve connection wherever it is running and I was trying to understand how this is feasible.
Attached you can find the docker-compose.yml I am using(attached as .txt because of github's restrictions). One of the services is postgis.
[docker-compose.txt](https://github.com/gmouchakis/docker-postgis/files/432022/docker-compose.txt)

**Comment by gmouchakis** [comment]
The name of the service is used only in the scope of the compose file. To find out more on how a container can connect to another container using the name of the container please check out http://docs.master.dockerproject.org/engine/userguide/networking/configure-dns/
